### ISSUE TITLE
Cross domain access denied

### ISSUE THREAD

**Issue by janeshdev** [coder-alpha/Einthusan.bundle#10]
Hi I was trying your plugin to see if it works. I keep getting the following message. 
![image](https://cloud.githubusercontent.com/assets/3325086/20501609/757d3b40-afef-11e6-96cc-86e87c100e03.png)

Could you please help with this issue ?

**Comment by coder-alpha** [comment]
http://forums.plex.tv/discussion/165072/rel-einthusan-channel-indian-movies/p1 has more info on known issues and solutions.

You can also view this video on how to fix cross domain issues. https://www.youtube.com/watch?v=Kyn1q7A50lw
