### ISSUE TITLE
PlugIn Broken after einthusan new release

### ISSUE THREAD

**Issue by vkakadia** [coder-alpha/Einthusan.bundle#11]
Hi,

Thanks much for making this plug-in available. It is really useful and making the difference. However, it is broken again after new einthusan release with new UI and other useful features.

Please provide a fix.

Thanks,
Vaibhav

**Comment by mmm8u** [comment]
Any fix available for the new einthusan UI ? Thanks

**Comment by nitinb30** [comment]
Yes. Plugin is not working for Roku after new Website changes. Appreciate if fix/updated plugin is released.

**Comment by coder-alpha** [comment]
Please read the instruction on the Plex forum thread and then try v0.08.
