### ISSUE TITLE
Not working for Plex Server

### ISSUE THREAD

**Issue by rajaindra** [coder-alpha/Einthusan.bundle#13]
Error "the channel seems broken, no data returned". Tried it on Plug-in 0.06 and reverted to 0.05 still no luck. Happens on Plex client using Samsung tv and Roku2 box.

**Comment by rdudeja1133** [comment]
Please fix this bundle so we can watch movies

Regards
RD

**Comment by coder-alpha** [comment]
Please read the instruction on the Plex forum thread and then try v0.08.
