### ISSUE TITLE
<MovieName> could not be fetched ! PMS on Windows 10 & Plex client on Roku and Web

### ISSUE THREAD

**Issue by rsquarev** [coder-alpha/Einthusan.bundle#17]
Hi, I installed 0.9 version and followed the same steps shown in main page. I can browse through movies, but cannot play any movie. I receive error message "<Movie Name>... could not be fetched !"

PMS Version 1.3.3.3148
PMS Host: Windows 10
Clients tried: Web, Plex on Roku.

**Comment by coder-alpha** [comment]
Please confirm Python 2.7.13 and Firefox was installed and path set as in example.
Please provide the einthusan channel log files.

**Comment by rsquarev** [comment]
trailing backslash was missing in plugin setting. correcting that fixed the problem

**Comment by jsinghgithub** [comment]
Hi,

First of all, thanks for fixing the plugin for new changes. 

I updated the channel today, and tested on Chrome. Still getting the same error. Is there anything I need to change on my side?

If you need logs then how do I get the logs to send?

Thanks

**Comment by jsinghgithub** [comment]
To add, some videos work but some fail with above error

**Comment by coder-alpha** [comment]
@jsinghgithub 

https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files

Yes, logs would be helpful. I would only need the plugin logs.
`...\Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.plugins.einthusan.log` and the numbered ones as well.

Also, please make a separate issue when posting with yours. Thanks.
