### ISSUE TITLE
Does not work any more in Roku etc

### ISSUE THREAD

**Issue by vimemail** [coder-alpha/Einthusan.bundle#19]
have the version 12 it keeps saying content cannot be found.  Can go through einthusan.com which redirects to einthusan.tv but Plex does not finds any content..  Not being able to use einthusan app for couple of months now

**Comment by coder-alpha** [comment]
Did you follow the new directions of setting up the requirements and paths ?
What OS ?
Please provide einthusan channel log.

**Comment by vimemail** [comment]
My Plex server is running on Windows 10 and I tried with Roku-3, Roku-4 and Apple TV-4 and none of them works. When I click o any menus options in Einthusan -hotpicks , year etc.. it just says sorry content not available. I am able to to Einthusan.com (redirects to einthusan.tv) using any of my computer browser just fine. So its not the blocked. In Any client Roku or Apple TV it does not work

**Comment by vimemail** [comment]
I just saw i was running older version of Plex Media server 1.0.3.2461..instead of min needed 1.3.3.3148.
I upgraded it now. Seems to get the menus now but seems to be getting timeout error now.. I will play around more to see if I am able to make it work. Thanks

**Comment by vimemail** [comment]
"Timeout error occured!" on selecting any movies in Einthusan through any menu selection

**Comment by coder-alpha** [comment]
Did you follow the new directions of setting up the requirements and paths ?
Did you install Firefox and define its path in the channel prefs ?
Please provide einthusan channel log.

**Comment by vimemail** [comment]
Finally, I missed that we need to have Firefox installed in Windows computer!! I did it along with updating the version for Plex Media server. Now it works in all client !! Sorry for not reading the installation instruction fully. Great Work:) I can enjoy the channel after a long gap. Thanks for all your help and good work.
