### ISSUE TITLE
Not working on plex anymore.

### ISSUE THREAD

**Issue by cksodhi** [coder-alpha/Einthusan.bundle#2]
Hi coder-alpha,

The plugin isn't working anymore. I get the "There was a problem playing this item." in the web interface and the movies dont play on roku plex either.

Please help.

This plugin is the most awesome thing on plex. Please fix it. :)

Thanks,
Charan

**Comment by nitinb30** [comment]
Yes. Correct. Plugin is not working with plex. Please fix it. I agree best plugin for Plex..

**Comment by cksodhi** [comment]
Hello @coderalpha .... Please fix it? :(

**Comment by coder-alpha** [comment]
Merged @Twoure 's fixes. Try now.

**Comment by nitinb30** [comment]
Thanks for the fix Coder-Alpha. Unfortunately I am still seeing error while playing movie..

Can you please have a look? thanks!!

![plex](https://cloud.githubusercontent.com/assets/20882517/17645938/2f5f966e-6182-11e6-868a-5b333ee2eac1.PNG)

**Comment by coder-alpha** [comment]
Using a browser might give you this error. You can try the following what @Twoure has suggested "Set your desired Plex Client's Direct Play/Stream to OFF/False".

**Comment by nitinb30** [comment]
Thanks! It solved the issue. Working like chime again.

Much appreciated...

**Comment by coder-alpha** [comment]
Great, thanks for reporting back !

**Comment by rdudeja1133** [comment]
I am still getting same message. Not able to play movies

**Comment by stormier1** [comment]
Hi einthusan has again stopped working. I get the error "this channel is not responding". Other channels working fine. Can you suggest solution or update einthusan.bundle ?

**Comment by stormier1** [comment]
I can go down the movie menu tree a few steps, but then it doesn't show the movie list by categories. in other words its not going all the way down to the movie file to play. goes a few steps and then "this channel is not responding" error
