### ISSUE TITLE
Einthusan.bundle doesnt work on samsung tv plex app 

### ISSUE THREAD

**Issue by nareshrokz** [coder-alpha/Einthusan.bundle#21]
it goes to the movies but it mentions request could not be completed.The requested item could not be found. Please fix this. This is one of the best functions in the plex app.

Naresh

**Comment by coder-alpha** [comment]
which version of the plugin are you using ? please use latest 0.13 if not already.
what OS and PMS version ?
can you provide your channel log ?

**Comment by coder-alpha** [comment]
Assuming this issue is resolved. Please post logs using latest version if issue persists.
