### ISSUE TITLE
Einthusan movie playback on Samsung Plex app does not work

### ISSUE THREAD

**Issue by sshekhar22** [coder-alpha/Einthusan.bundle#23]
Using the latest version of the Plex server: `Version 1.5.3.3580-4b377d295` and that of the Einthusan plugin: `Commit SHA1: 4a46ddb6d12c14f21432dd789c66f764a3730da1`

Attaching portion of the log where I tried to play a movie on my Samsung Plex app. Playing trailers of movies seems to work fine.

I am running my Plex server on my Mac OSX: `Version: 10.12.4`

[EinthusanSamsung.docx]

**Comment by coder-alpha** [comment]
Hi, please provide the channel plugin logs > com.plexapp.plugins.einthusan.log and ones that are numbered found under `...\Plex Media Server\Logs\PMS Plugin Logs\`. 
Enable debug under the channel Preferences option then try playing a movie and then provide the log files.

Is your issue only on the Samsung Plex App and not when using Plex-Web ?

**Comment by sshekhar22** [comment]
Yes, my issue is only on the Samsung Plex app. I can play the movie successfully in my browser. I enabled debugging in Einthusan preferences and tried to play the movie. Whne I downloaded the logs, the zip file it created is attached here. I do not see the path you mentioned above though, don't see any com.plexapp.plugins.einthusan.log file in here.

Again, I am using an iMac as my server, so you have any instructions on how to create that log file, I can try and do that. Meanwhile, here is the complete ZIP file that I dumped right after trying to play a movie on my Samsung TV Plex app.

[Plex Media Server Logs_2017-04-09_20-37-43.zip]

**Comment by coder-alpha** [comment]
https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files

Before providing the Channel log please enable send debug info to server option on your Samsung Plex App and then again try a movie playback.

You might also want to try setting Direct Play or Transcoding on your Samsung Plex App to see if that helps in playback. The default is Auto. What ver. of Samsung Plex App are you using ? Is it the one by Orca or from Samsung ?

Just to confirm when you say "I can play the movie successfully in my browser" you mean Plex-Web and not on their website, right ?

**Comment by sshekhar22** [comment]
Thanks for the info. I tried the different settings from Direct Streaming,
Direct Play and Transcoding but none of them helped.

The app I am using is from 'HD1080 and Orca', it seems. The version is
1.015.

And yes, I did mean Plex-Web, not on Einthusan site directly.

Attaching the logs here. The einthusan.log and system.log include my latest
attempt to play the movie. The others (.1, .2 etc.) are older but I
included them here anyways.

Let me know if you need anything else.

Meanwhile, I am going to see if I can find the Samsung version of the app
and give that a shot.

Thanks,
Shashank.


Sent from my T-Mobile 4G LTE Device

**Comment by sshekhar22** [comment]
Hey,
A quick update. In looking for the Samsung app, I realised my app was an older version. I upgraded to the latest one and now I am able to play the movie.
So looks like, the latest versions are good to go.
Thanks for your prompt responses and trying to help with the issue. You can close the issue now.
Thanks,Shashank.
Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Shashank Shekhar <mail2shekhars@gmail.com> Date: 4/10/17  6:53 PM  (GMT-07:00) To: "coder-alpha/Einthusan.bundle" <reply@reply.github.com>, "coder-alpha/Einthusan.bundle" <Einthusan.bundle@noreply.github.com> Cc: Author <author@noreply.github.com> Subject: Re: [coder-alpha/Einthusan.bundle] Einthusan movie playback on Samsung Plex app does not work (#23) 
Thanks for the info. I tried the different settings from Direct Streaming, Direct Play and Transcoding but none of them helped.
The app I am using is from 'HD1080 and Orca', it seems. The version is 1.015.
And yes, I did mean Plex-Web, not on Einthusan site directly.
Attaching the logs here. The einthusan.log and system.log include my latest attempt to play the movie. The others (.1, .2 etc.) are older but I included them here anyways.
Let me know if you need anything else.
Meanwhile, I am going to see if I can find the Samsung version of the app and give that a shot.
Thanks,Shashank.

Sent from my T-Mobile 4G LTE Device
