### ISSUE TITLE
Can you provide for login area for members of einthusan 

### ISSUE THREAD

**Issue by R1en** [coder-alpha/Einthusan.bundle#25]
streaming would be better

**Comment by coder-alpha** [comment]
Unless I buy an account I can't create that section so its not high on my priority list. Also, the site in inaccessible from the country where I am traveling.

**Comment by rdudeja1133** [comment]
I don’t think we need account thing. It’s only to avoid ads while you are watching on web. With Einthusan App we don’t see any ads so it’s not worth it.

Sent from my iPhone

On Jun 13, 2018, at 7:31 AM, Coder-Alpha <notifications@github.com<mailto:notifications@github.com>> wrote:


Unless I buy an account I can't create that section so its not high on my priority list. Also, the site in inaccessible from the country where I am traveling.

**Comment by R1en** [comment]
Members have faster streaming of the content without any hiccups.. and also have exclusive content ..

Sent from Mobile phone
________________________________

**Comment by rdudeja1133** [comment]
I am a premium member since 2013

Sent from my iPhone

On Jun 13, 2018, at 10:33 AM, R1en <notifications@github.com<mailto:notifications@github.com>> wrote:

Members have faster streaming of the content without any hiccups.. and also have exclusive content ..

Sent from Mobile phone
________________________________

**Comment by R1en** [comment]
Got it..
But this was mentioned on their website[Image]
i experienced better speeds..

Sent from Mobile phone
________________________________

**Comment by rdudeja1133** [comment]
It’s only for website but when you are using plex... You are getting same speed as premium member

Sent from my iPhone

On Jun 13, 2018, at 11:01 AM, R1en <notifications@github.com<mailto:notifications@github.com>> wrote:

Got it..
But this was mentioned on their website[Image]
i experienced better speeds..

Sent from Mobile phone
________________________________

**Comment by rdudeja1133** [comment]
Please make sure your plex device is hard wire so you can get better speed

Sent from my iPhone

On Jun 13, 2018, at 11:01 AM, R1en <notifications@github.com<mailto:notifications@github.com>> wrote:

Got it..
But this was mentioned on their website[Image]
i experienced better speeds..

Sent from Mobile phone
________________________________
