### ISSUE TITLE
Einthusan plugin in macbook

### ISSUE THREAD

**Issue by Daher25** [coder-alpha/Einthusan.bundle#26]
Hi,

I've installed and followed the instructions (hopefully) and it worked almost, but not the final step.

machine: macbook pro 10.12.6
pMS:Version 1.13.2.5154  (says it is upto date)
Firefox: 50 (downgraded from 56)
TV: Sony with androidtv
Einthusan.bundle V0.14

I installed firefox/python/plex and einthusan plugin (0.14) 
I'm able to access the plugin and see contents. When I open any movie in macbook, it shows 'timeout error occured' (same from plex app from tv).
Using proxy for connection:
firefox path: /Applications/Firefox/Contents/MacOS/firefox

Please help....

Thanks,
Balaji

**Comment by coder-alpha** [comment]
Use the following settings... except for location which would be based closest to you.

![image](https://user-images.githubusercontent.com/10291660/42408399-b4bf4500-81e9-11e8-899f-e6b4f13b1be1.png)

**Comment by Daher25** [comment]
Hi,

Thank you so much !!!! It worked. Now I can play the files in macbook.

still got one problem with TV. It can play trailers (small videos) but problem with playing movies.
It seems to be more with PLEX. Please see the attached image. 
Also, did some googling on the error, but it is not leading to the final fix... 
https://forums.plex.tv/t/playback-has-stopped-because-the-connection-to-the-plex-media-server-has-been-lost/225743 


Error
![plex problem](https://user-images.githubusercontent.com/40903901/42415508-46df4592-8240-11e8-8f21-d7cf872b40d4.jpeg)

Please help me cross this final thing...

Thanks,
Balaji

**Comment by coder-alpha** [comment]
Since you can play the files on the Mac then the plugin is working fine as expected and the issue is not within the plugin.

The issue of not playing on the TV could be due to the media file not compatible with Direct Play on the TV. I would suggest enabling Transcoding on the TV to make the file format compatible for playback. YouTube trailers are transcoded for playback.
