### ISSUE TITLE
Cannot forward or reverse any movies on Plex/roku

### ISSUE THREAD

**Issue by cksodhi** [coder-alpha/Einthusan.bundle#5]
So I know you been working hard but I noticed that after the latest release forwarding and reversing the videos does not work anymore.

**Comment by coder-alpha** [comment]
The video is now presented as a m3u8 stream with .ts segments. I believe the flash player on their websites handles ff/rev fine but Plex for some reason does not at the moment. I will look into this as time permits. As of now its low on my todo list. Sorry.

**Comment by STEW1327** [comment]
can u send plex movies on now tv box 192.168.0.11

**Comment by coder-alpha** [comment]
Available as of v0.08.
