### ISSUE TITLE
Does not work on Plex Android client.

### ISSUE THREAD

**Issue by cksodhi** [coder-alpha/Einthusan.bundle#6]
No videos work on Android client.

**Comment by coder-alpha** [comment]
For Einthusan you should "Set your desired Plex Client's Direct Play and Stream to OFF/False", it should work then.

**Comment by coder-alpha** [comment]
http://forums.plex.tv/discussion/165072/rel-einthusan-channel-indian-movies/p1 has more info on known issues and solutions.

You can also view this video on how to fix cross domain issues. https://www.youtube.com/watch?v=Kyn1q7A50lw
