### ISSUE TITLE
Forwarding issue in Apple TV 4

### ISSUE THREAD

**Issue by vimemail** [coder-alpha/Einthusan.bundle#7]
I come back to report as I closed my incident earlier. Not possible to forward any video in Apple TV 4 and continue watching any Einthusan movie. I do have ROKU 3 and it works perfectly fine.

**Comment by coder-alpha** [comment]
I have noticed issue with FF/Rev. and it might need further investigation since now they dont provide an mp4 video for playback but an m3u8 stream with .ts segments. I will try and look into it as time permits.

**Comment by coder-alpha** [comment]
Please read the instruction on the Plex forum thread and then try v0.08.  FF/REW available with latest version.
