### ISSUE TITLE
Not able to play Einthusan

### ISSUE THREAD

**Issue by rdudeja1133** [coder-alpha/Einthusan.bundle#9]
Not able to play Einthusan.. Can some one help

**Comment by coder-alpha** [comment]
Please read the first post in this thread (https://forums.plex.tv/discussion/165072) for known issues and how to resolve.

Probably you need to disable Direct Play/Stream on your client.

**Comment by coder-alpha** [comment]
http://forums.plex.tv/discussion/165072/rel-einthusan-channel-indian-movies/p1 has more info on known issues and solutions.

You can also view this video on how to fix cross domain issues. https://www.youtube.com/watch?v=Kyn1q7A50lw
